### ISSUE TITLE
[Question] Events not show with DemoData

### ISSUE THREAD

**Issue by hoangtrieukd** [StephenChou1017/react-big-scheduler#82]
This is my component: [https://jsfiddle.net/hoangtrieukd/s2d0rpy9/](url)
But events not show:
![image](https://user-images.githubusercontent.com/15377683/50746210-8e980a80-1260-11e9-9afe-846dee996e58.png)
What's wrong with me!

**Comment by StephenChou1017** [comment]
@hoangtrieukd 
You can try [this demo](https://github.com/StephenChou1017/react-big-scheduler-demo), it should work.

**Comment by MikeDev96** [comment]
@hoangtrieukd have you setup the drag and drop context? I had the same issue where no events would show, but wrapping the component with a DND context fixes it.

**Comment by bl5ck** [comment]
I also have this problem. Used react-styleguidist to serve the docs site and it also doesn't show events. I tried your solution by copying exactly the script content above, but still the same.

**Comment by bl5ck** [comment]
I tried with the simplest app version (my current app without sagas, reducers, containers, etc...) and it still shows blank scheduler.

**Comment by bl5ck** [comment]
It seems to have the same issue with this bug report:
[https://github.com/StephenChou1017/react-big-scheduler/issues/88](https://github.com/StephenChou1017/react-big-scheduler/issues/88)

**Comment by smoczynskicitiz** [comment]
I was having some trouble too to display demo events.

What you need to do is, like the example, create this file (https://github.com/StephenChou1017/react-big-scheduler-demo/blob/master/src/withDnDContext.js) in your project and then, call it from your Component and wrapped it.

```javascript

import withDragDropContext from "../../utils/withDnDContext";

...

export default compose(
  withDragDropContext,
  ...
)(Component);

```

It should be ok after that.

**Comment by ritapetillo** [comment]
Hi, I'm having the same problem with events not showing up in the table. 
I tried all the solution mention above, but none of them worked.

Any clue how to resolve this problem?

"react": "^16.7.0",
"react-big-scheduler": "^0.2.5",
"react-dnd": "^7.0.2",
 "react-dnd-html5-backend": "^7.0.2",
"react-dom": "^16.7.0",

**Comment by smoczynskicitiz** [comment]
Hello,

Try to use the following packages with these versions : 

"react-dnd": "^5.0.0",
"react-dnd-html5-backend": "^5.0.1",

**Comment by Krankypanky** [comment]
Hello, 
I'm having the same problem with missing events. I tried downgrading several libs, but without success
`import React from "react";
import moment from "moment";
import Scheduler, {CellUnits, DATE_FORMAT, DemoData, SchedulerData, ViewTypes} from "react-big-scheduler";
import {DragDropContext} from 'react-dnd'
import HTML5Backend from 'react-dnd-html5-backend'



class BookingScheduler extends React.Component {
    constructor(props) {
        super(props);

        let schedulerData = new SchedulerData(moment().format(DATE_FORMAT), ViewTypes.Custom, false, false, {
            customCellWidth: 30,
            nonAgendaDayCellHeaderFormat: "M/D|HH:mm",
            views: [
                {viewName: "One day", viewType: ViewTypes.Custom, showAgenda: false, isEventPerspective: false},
                {viewName: "One week", viewType: ViewTypes.Custom1, showAgenda: false, isEventPerspective: false},
                {viewName: "One month", viewType: ViewTypes.Custom2, showAgenda: false, isEventPerspective: false},
            ],
        }, {
            getCustomDateFunc: this.getCustomDate,
            isNonWorkingTimeFunc: this.isNonWorkingTime
        });
        schedulerData.localeMoment.locale("en");
        schedulerData.setResources(DemoData.resources);
        schedulerData.setEvents(DemoData.events);
        this.state = {
            viewModel: schedulerData,
        }
    }

    render() {
        const {viewModel} = this.state;

        return (
            <div>
                <Scheduler schedulerData={viewModel}
                           prevClick={this.prevClick}
                           nextClick={this.nextClick}
                           onSelectDate={this.onSelectDate}
                           onViewChange={this.onViewChange}
                           eventItemClick={this.eventClicked}
                           viewEventClick={this.ops1}
                           viewEventText="Ops 1"
                           viewEvent2Text="Ops 2"
                           viewEvent2Click={this.ops2}
                           updateEventStart={this.updateEventStart}
                           updateEventEnd={this.updateEventEnd}
                           moveEvent={this.moveEvent}
                           newEvent={this.newEvent}
                />
            </div>
        )
    }

    prevClick = (schedulerData) => {
        schedulerData.prev();
        schedulerData.setEvents(DemoData.events);
        this.setState({
            viewModel: schedulerData
        })
    };

    nextClick = (schedulerData) => {
        schedulerData.next();
        schedulerData.setEvents(DemoData.events);
        this.setState({
            viewModel: schedulerData
        })
    };

    onViewChange = (schedulerData, view) => {
        schedulerData.setViewType(view.viewType, view.showAgenda, view.isEventPerspective);
        schedulerData.config.customCellWidth = view.viewType === ViewTypes.Custom ? 30 : 80;
        schedulerData.setEvents(DemoData.events);
        this.setState({
            viewModel: schedulerData
        })
    };

    onSelectDate = (schedulerData, date) => {
        schedulerData.setDate(date);
        schedulerData.setEvents(DemoData.events);
        this.setState({
            viewModel: schedulerData
        })
    };

    eventClicked = (schedulerData, event) => {
        alert(`You just clicked an event: {id: ${event.id}, title: ${event.title}}`);
    };

    ops1 = (schedulerData, event) => {
        alert(`You just executed ops1 to event: {id: ${event.id}, title: ${event.title}}`);
    };

    ops2 = (schedulerData, event) => {
        alert(`You just executed ops2 to event: {id: ${event.id}, title: ${event.title}}`);
    };

    newEvent = (schedulerData, slotId, slotName, start, end, type, item) => {
        if (window.confirm(`Do you want to create a new event? {slotId: ${slotId}, slotName: ${slotName}, start: ${start}, end: ${end}, type: ${type}, item: ${item}}`)) {

            let newFreshId = 0;
            schedulerData.events.forEach((item) => {
                if (item.id >= newFreshId)
                    newFreshId = item.id + 1;
            });

            let newEvent = {
                id: newFreshId,
                title: "New event you just created",
                start: start,
                end: end,
                resourceId: slotId,
                bgColor: "purple"
            }
            schedulerData.addEvent(newEvent);
            this.setState({
                viewModel: schedulerData
            })
        }
    }

    updateEventStart = (schedulerData, event, newStart) => {
        if (window.confirm(`Do you want to adjust the start of the event? {eventId: ${event.id}, eventTitle: ${event.title}, newStart: ${newStart}}`)) {
            schedulerData.updateEventStart(event, newStart);
        }
        this.setState({
            viewModel: schedulerData
        })
    }

    updateEventEnd = (schedulerData, event, newEnd) => {
        if (window.confirm(`Do you want to adjust the end of the event? {eventId: ${event.id}, eventTitle: ${event.title}, newEnd: ${newEnd}}`)) {
            schedulerData.updateEventEnd(event, newEnd);
        }
        this.setState({
            viewModel: schedulerData
        })
    }

    moveEvent = (schedulerData, event, slotId, slotName, start, end) => {
        if (window.confirm(`Do you want to move the event? {eventId: ${event.id}, eventTitle: ${event.title}, newSlotId: ${slotId}, newSlotName: ${slotName}, newStart: ${start}, newEnd: ${end}`)) {
            schedulerData.moveEvent(event, slotId, slotName, start, end);
            this.setState({
                viewModel: schedulerData
            })
        }
    }

    getCustomDate = (schedulerData, num, date = undefined) => {
        const {viewType} = schedulerData;
        let selectDate = schedulerData.startDate;
        if (date !== undefined)
            selectDate = date;

        let startDate = num === 0 ? selectDate :
                schedulerData.localeMoment(selectDate).add(num, "day").format(DATE_FORMAT),
            endDate = schedulerData.localeMoment(startDate).format(DATE_FORMAT),
            cellUnit = CellUnits.Hour;
        if (viewType === ViewTypes.Custom1) {
            let monday = schedulerData.localeMoment(selectDate).startOf("week").format(DATE_FORMAT);
            startDate = num === 0 ? monday : schedulerData.localeMoment(monday).add(num, "week").format(DATE_FORMAT);
            endDate = schedulerData.localeMoment(startDate).endOf("week").format(DATE_FORMAT);
            cellUnit = CellUnits.Day;
        } else if (viewType === ViewTypes.Custom2) {
            let firstDayOfMonth = schedulerData.localeMoment(selectDate).startOf("month").format(DATE_FORMAT);
            startDate = num === 0 ? firstDayOfMonth : schedulerData.localeMoment(firstDayOfMonth).add(num, "month").format(DATE_FORMAT);
            endDate = schedulerData.localeMoment(startDate).endOf("month").format(DATE_FORMAT);
            cellUnit = CellUnits.Day;
        }

        return {
            startDate,
            endDate,
            cellUnit
        };
    };

    isNonWorkingTime = (schedulerData, time) => {
        const {localeMoment} = schedulerData;
        if (schedulerData.cellUnit === CellUnits.Hour) {
            let hour = localeMoment(time).hour();
            if (hour < 1)
                return true;
        }
        else {
            let dayOfWeek = localeMoment(time).weekday();
            if (dayOfWeek === 0 || dayOfWeek === 6)
                return true;
        }

        return false;
    }
}


export default DragDropContext(HTML5Backend)(BookingScheduler)
`

**Comment by Krankypanky** [comment]
Resolved my issue,
had to downgrade to:

"react-dnd": "^5.0.0",
"react-dnd-html5-backend": "^5.0.1"

At my first attempt i missed the ^ flag, so it got still installed in the wrong version. Seems that is also compatible with react@16.8.

thanks @smoczynskicitiz !

**Comment by reenan** [comment]
@smoczynskicitiz  and @Krankypanky this indeed fixed the issue for me as well. 
@StephenChou1017 is there any plan to provide support for the latest versions of react-dnd? Thanks!

**Comment by StephenChou1017** [comment]
@reenan I'll try:-)

**Comment by tuantq10** [comment]
Dear @StephenChou1017 ,

I was having some trouble too to display demo events. I have followed suggestion from @Krankypanky, but still not woking.

This is my packages:

> "axios": "^0.18.0",
"braces": "^2.3.2",
"history": "^4.7.2",
"i18next": "^15.0.2",
"i18next-browser-languagedetector": "^3.0.0",
"i18next-xhr-backend": "^2.0.0",
"jquery": "^3.3.1",
"moment": "^2.24.0",
"numeral": "^2.0.6",
"react": "16.8.3",
"react-big-scheduler": "^0.2.6",
"react-dnd": "5.0.0",
"react-dnd-html5-backend": "5.0.1",
"react-dom": "16.8.3",
"react-i18next": "^10.3.0",
"react-redux": "^6.0.0",
"react-router": "^4.3.1",
"react-router-dom": "^4.3.1",
"recompose": "^0.30.0",
"redux": "^4.0.1",
"redux-thunk": "^2.3.0",
"toastr": "^2.1.4",
"validator": "^10.11.0",
"wix-style-react": "6.7.3"

**Comment by reenan** [comment]
> Dear @StephenChou1017 ,
> 
> I was having some trouble too to display demo events. I have followed suggestion from @Krankypanky, but still not woking.

@tuantq10 don't forget to delete the node_modules folder and re-run npm i in order to setup the correct versions.

**Comment by amansor788** [comment]
export default DragDropContext(HTML5Backend)(Calendar);
@hoangtrieukd  this solution worked for me!!

**Comment by QaisernRiaz** [comment]
> @hoangtrieukd
> You can try [this demo](https://github.com/StephenChou1017/react-big-scheduler-demo), it should work.

plese check this #125 problem.

**Comment by Ramesraina** [comment]
Hi,
    I was having some trouble integrate this scheduler into my application.

    When i am trying with the default demoData which already this scheduler have is working fine. If i will remove all the data except resources, it is working fine only. But if i will remove any resource from that list, It shows,  "**Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**".

**Comment by premji1528** [comment]
Try This https://github.com/StephenChou1017/react-big-scheduler/issues/117#issuecomment-704983192

**Comment by KennanObura** [comment]
If anyone still have the same issue, these versions seem to work
   `"react-dnd": "^7.5.0",
    "react-dnd-html5-backend": "^7.5.0",
    "react-dom": "^17.0.2", 
    "react-big-scheduler": "^0.2.7",`

**Comment by ppmview** [comment]
Still now working

> Try This [#117 (comment)](https://github.com/StephenChou1017/react-big-scheduler/issues/117#issuecomment-704983192)

**Comment by ppmview** [comment]
> If anyone still have the same issue, these versions seem to work `"react-dnd": "^7.5.0", "react-dnd-html5-backend": "^7.5.0", "react-dom": "^17.0.2", "react-big-scheduler": "^0.2.7",`

Not working
